### ISSUE TITLE
Additions/Removals and how they affect stats

### ISSUE THREAD

**Issue by carranca** [AlecStrong/conway#2]
Would be dope to be able to see how someone's code contributions are spread between additions and removals.

This is purely self-serving, because my ego is damaged and needs some TLC:
`mcarranca accounts for 17.43% of [app]`
`mcarranca writes 34.54% of their code in [app]`

So e.g.:

[MODIFIED] `carranca writes 47% of their code in app (of which 95% are removals and 5% are additions)`
[MODIFIED] `carranca accounts for 16% of code removals in app`
[MODIFIED] `carranca accounts for 67% of code additions in app`
[MODIFIED] `carranca writes 54% of their code in app`
[NEW] `code removals account for 62% of carranca's contributions`

I've started playing around with it, just wanted to socialize for ideas/objections

**Comment by AlecKazakova** [comment]
Makes sense to me!

**Comment by AlecKazakova** [comment]
done
